### ISSUE TITLE
Panic when writes to cloudwatch fail, not a very helpful error message

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [krestivo-kdinfotech/systemd-cloud-watch#2]
```
 panic: runtime error: invalid memory address or nil pointer dereference

   [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7953f4]

   goroutine 6 [running]:

   github.com/krestivo-kdinfotech/systemd-cloud-watch/cloud-watch.(*CloudWatchJournalRepeater).WriteBatch.func2(0x82d880, 0xc4206ec240)
         /go/src/github.com/krestivo-kdinfotech/systemd-cloud-watch/cloud-watch/cloudwatch_journal_repeater.go:100 +0x104

   github.com/krestivo-kdinfotech/systemd-cloud-watch/cloud-watch.(*CloudWatchJournalRepeater).WriteBatch(0xc420072eb0, 0xc42060a000, 0x32, 0x40, 0x0, 0x0)
         /go/src/github.com/krestivo-kdinfotech/systemd-cloud-watch/cloud-watch/cloudwatch_journal_repeater.go:175 +0xe33

   github.com/krestivo-kdinfotech/systemd-cloud-watch/cloud-watch.(*Runner).sendBatch(0xc42007b220)
         /go/src/github.com/krestivo-kdinfotech/systemd-cloud-watch/cloud-watch/workers.go:45 +0xde

   github.com/krestivo-kdinfotech/systemd-cloud-watch/cloud-watch.(*Runner).addToCloudWatchBatch(0xc42007b220, 0xc42023ac60)
         /go/src/github.com/krestivo-kdinfotech/systemd-cloud-watch/cloud-watch/workers.go:36 +0x79

   github.com/krestivo-kdinfotech/systemd-cloud-watch/cloud-watch.NewRunnerInternal.func1(0x7d1360, 0xc42023ac60)
         /go/src/github.com/krestivo-kdinfotech/systemd-cloud-watch/cloud-watch/workers.go:77 +0x45

   github.com/advantageous/go-qbit/qbit.(*BaseReceiveQueueListener).Receive(0xc420056ac0, 0x7d1360, 0xc42023ac60)
         /go/src/github.com/advantageous/go-qbit/qbit/listener.go:74 +0x3e

   github.com/advantageous/go-qbit/qbit.manageQueue(0x2710, 0x998220, 0xc4200e5c20, 0x999520, 0xc4201c8810, 0x9994c0, 0xc420056ac0)
         /go/src/github.com/advantageous/go-qbit/qbit/queue-manager.go:111 +0xa4

   created by github.com/advantageous/go-qbit/qbit.(*BasicQueueManager).startListener
         /go/src/github.com/advantageous/go-qbit/qbit/queue-manager.go:45 +0xd1

```

Root cause was a write problem with the log stream in AWS. The go could should check for write problems and report them in a more useful way.

**Comment by krestivo-kdinfotech** [comment]
```
Apr 17 20:26:06 bblaze-test docker[3127]: main ERROR: 2020/04/17 20:26:06 workers.go:47: Failed to write to cloudwatch batch size = : %d %s %v 0 failed to put events: : InvalidParameterException: The batch of log events in a single PutLog

Apr 17 20:26:06 bblaze-test docker[3127]: repeater ERROR: 2020/04/17 20:26:06 cloudwatch_journal_repeater.go:202: Error from
putEvents : InvalidParameterException: The batch of log events in a single PutLogEvents request cannot span more```
```

**Comment by krestivo-kdinfotech** [comment]
Going to try to add some debug statements and see how that goes.
